version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: marketsystem-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: marketsystem
      MONGO_INITDB_ROOT_PASSWORD: marketsystem

volumes:
  mongodb_data:
